table Dim_Legionella_metric
	lineageTag: 5cbe5e79-1b88-43d5-83d1-ea777039ef57

	column Metric
		dataType: string
		lineageTag: 649acd82-216c-4c61-bca2-c7c5550421d0
		summarizeBy: none
		sourceColumn: Metric

		annotation SummarizationSetBy = Automatic

	column Legionella_metric_key
		dataType: int64
		formatString: 0
		lineageTag: acaeb95d-e771-44c2-adf5-e7de73d6a81b
		summarizeBy: none
		sourceColumn: Legionella_metric_key

		annotation SummarizationSetBy = Automatic

	partition Dim_Legionella_metric = m
		mode: import
		queryGroup: Legionella
		source =
				let
				    Source = Legionella_source,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"Metric"}),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Other Columns", "Index", 1, 1, Int64.Type),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Index",{{"Index", "Legionella_metric_key"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

