table Dim_Asbestos_metric
	lineageTag: f8321695-10a2-4826-8d76-e695db16e282

	column Metric
		dataType: string
		lineageTag: 7a335fa6-4b4f-4549-a441-d38a96f38fae
		summarizeBy: none
		sourceColumn: Metric

		annotation SummarizationSetBy = Automatic

	column Asbestos_metric_key
		dataType: int64
		formatString: 0
		lineageTag: 48e13a3d-27b8-4673-a45f-f8257cb431d4
		summarizeBy: none
		sourceColumn: Asbestos_metric_key

		annotation SummarizationSetBy = Automatic

	partition Dim_Asbestos_metric = m
		mode: import
		queryGroup: Asbestos
		source =
				let
				    Source = Asbestos_source,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"Metric"}),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Other Columns", "Index", 1, 1, Int64.Type),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Index",{{"Index", "Asbestos_metric_key"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

