table Fact_Asbestos
	lineageTag: 71c95dea-2bc8-4d1f-96b3-54001d2357cb

	column Target
		dataType: int64
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 9c011592-2b70-4fc8-881b-a53746b2dbd8
		summarizeBy: sum
		sourceColumn: Target

		annotation SummarizationSetBy = Automatic

	column Actual
		dataType: int64
		lineageTag: 2cea7806-d330-4ee0-9c0f-f2fd579fd076
		summarizeBy: sum
		sourceColumn: Actual

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Asbestos_metric_key
		dataType: int64
		formatString: 0
		lineageTag: ebddb476-76a0-4c45-9f59-6337785ca679
		summarizeBy: none
		sourceColumn: Asbestos_metric_key

		annotation SummarizationSetBy = Automatic

	column Rag_key
		dataType: int64
		formatString: 0
		lineageTag: 6bf4e044-fcce-43e8-9dfe-46a76821ddfc
		summarizeBy: none
		sourceColumn: Rag_key

		annotation SummarizationSetBy = Automatic

	partition Fact_Asbestos = m
		mode: import
		queryGroup: Asbestos
		source =
				let
				    Source = Asbestos_source,
				    #"Merged Queries" = Table.NestedJoin(Source, {"Metric"}, Dim_Asbestos_metric, {"Metric"}, "Dim_Asbestos_metric", JoinKind.LeftOuter),
				    #"Expanded Dim_Asbestos_metric" = Table.ExpandTableColumn(#"Merged Queries", "Dim_Asbestos_metric", {"Asbestos_metric_key"}, {"Asbestos_metric_key"}),
				    #"Merged Queries1" = Table.NestedJoin(#"Expanded Dim_Asbestos_metric", {"RAG"}, Dim_RAG, {"RAG"}, "Dim_RAG", JoinKind.LeftOuter),
				    #"Expanded Dim_RAG" = Table.ExpandTableColumn(#"Merged Queries1", "Dim_RAG", {"Rag_key"}, {"Rag_key"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Expanded Dim_RAG",{"Metric", "RAG", "Notes"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Columns",{{"Actual", Int64.Type}, {"Target", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

