table Fact_Legionella
	lineageTag: 44bf40ac-1b03-4d59-81f1-2f83f2d5b282

	column Legionella_metric_key
		dataType: int64
		formatString: 0
		lineageTag: 3359c52c-e9ba-4152-9eb6-8fb2ff041350
		summarizeBy: none
		sourceColumn: Legionella_metric_key

		annotation SummarizationSetBy = Automatic

	column Rag_key
		dataType: int64
		formatString: 0
		lineageTag: 91cb8c10-22da-41d9-9944-ccc5bd173a8a
		summarizeBy: none
		sourceColumn: Rag_key

		annotation SummarizationSetBy = Automatic

	column Target
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 3dfb0bb8-ad20-441f-96f0-31c3515735b6
		summarizeBy: sum
		sourceColumn: Target

		annotation SummarizationSetBy = Automatic

	column Actual
		dataType: int64
		formatString: 0
		lineageTag: 14fddc1f-d408-4ab6-98bf-45acb3e282b4
		summarizeBy: sum
		sourceColumn: Actual

		annotation SummarizationSetBy = Automatic

	partition Fact_Legionella = m
		mode: import
		queryGroup: Legionella
		source =
				let
				    Source = Legionella_source,
				    #"Merged Queries" = Table.NestedJoin(Source, {"Metric"}, Dim_Legionella_metric, {"Metric"}, "Dim_Legionella_metric", JoinKind.LeftOuter),
				    #"Expanded Dim_Legionella_metric" = Table.ExpandTableColumn(#"Merged Queries", "Dim_Legionella_metric", {"Legionella_metric_key"}, {"Legionella_metric_key"}),
				    #"Merged Queries1" = Table.NestedJoin(#"Expanded Dim_Legionella_metric", {"RAG"}, Dim_RAG, {"RAG"}, "Dim_RAG", JoinKind.LeftOuter),
				    #"Expanded Dim_RAG" = Table.ExpandTableColumn(#"Merged Queries1", "Dim_RAG", {"Rag_key"}, {"Rag_key"}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Expanded Dim_RAG",{"Legionella_metric_key", "Rag_key", "Target", "Actual"})
				in
				    #"Removed Other Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

